version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    networks:
      - foundation-ui
    env_file:
      - .env
    volumes:
      - ./src/:/var/www/foundation
    tty: true


  nginx-server:
    restart: unless-stopped
    image: nginx:alpine
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - web
    ports:
      - "${NGINX_HOST_PORT}:80"
    networks:
      - foundation-ui

networks:
  foundation-ui:
    driver: bridge
