export default [
        {
          "id": 27,
          "name": "Abadin Jose",
          "first_name": "Jose",
          "last_name": "Abadin",
          "email": "dr@abadindental.com",
          "status": "inactive",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-11-14T18:29:29.000000Z"
        },
        {
          "id": 12,
          "name": "Abdehou Anahita",
          "first_name": "Anahita",
          "last_name": "Abdehou",
          "email": "kiuana@comcast.net",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 1,
          "name": "Abdelmonem Rafah",
          "first_name": "Rafah",
          "last_name": "Abdelmonem",
          "email": "rafahmonem@yahoo.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:17.000000Z"
        },
        {
          "id": 41,
          "name": "Abenaim Jonathan",
          "first_name": "Jonathan",
          "last_name": "Abenaim",
          "email": "drabenaim@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 4,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 51,
          "name": "Abraham Henry",
          "first_name": "Henry",
          "last_name": "Abraham",
          "email": "drhlh_idds@yahoo.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 43,
          "name": "Abrahams Howard",
          "first_name": "Howard",
          "last_name": "Abrahams",
          "email": "dr.abrahams@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 294,
          "name": "Abramowitz Craig",
          "first_name": "Craig",
          "last_name": "Abramowitz",
          "email": "cabramowitz@nedentalmanagement.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:21.000000Z"
        },
        {
          "id": 39,
          "name": "Agamov Andrey",
          "first_name": "Andrey",
          "last_name": "Agamov",
          "email": "welovebrt@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 2,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 35,
          "name": "Agarwal Anil",
          "first_name": "Anil",
          "last_name": "Agarwal",
          "email": "wintersetdental@yahoo.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 2,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 638,
          "name": "Ahdut Yoni",
          "first_name": "Yoni",
          "last_name": "Ahdut",
          "email": null,
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:26.000000Z"
        },
        {
          "id": 523,
          "name": "Ahmadi Mohammad",
          "first_name": "Mohammad",
          "last_name": "Ahmadi",
          "email": "1987dentist@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:24.000000Z"
        },
        {
          "id": 387,
          "name": "Ajdari Jurak",
          "first_name": "Jurak",
          "last_name": "Ajdari",
          "email": "jurak@mac.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:23.000000Z"
        },
        {
          "id": 610,
          "name": "Alfano Stephen",
          "first_name": "Stephen",
          "last_name": "Alfano",
          "email": "stephen@balboaislanddentistry.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": "1233567677",
          "num_of_locations": 2,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:26.000000Z"
        },
        {
          "id": 48,
          "name": "Alford Ken",
          "first_name": "Ken",
          "last_name": "Alford",
          "email": "doctor.alford@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 298,
          "name": "Ali Zarah",
          "first_name": "Zarah",
          "last_name": "Ali",
          "email": "zarahallh_idmd@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:21.000000Z"
        },
        {
          "id": 20,
          "name": "Amara Anu",
          "first_name": "Anu",
          "last_name": "Amara",
          "email": "nysadental@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        },
        {
          "id": 633,
          "name": "Amit Motwani",
          "first_name": "Motwani",
          "last_name": "Amit",
          "email": null,
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:26.000000Z"
        },
        {
          "id": 486,
          "name": "Ammons Michael",
          "first_name": "Michael",
          "last_name": "Ammons",
          "email": "mwammons@gmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": {
            "id": 100,
            "email": "susan@wm4d.com",
            "first_name": "Susan",
            "last_name": "Perez",
            "job_title": null,
            "organisation": null,
            "phone_number": null,
            "address": null,
            "pay_rate": null,
            "status": 1,
            "created_at": "2021-04-20T22:19:35.000000Z",
            "updated_at": "2021-04-20T22:58:28.000000Z"
          },
          "phone_number": "00",
          "num_of_locations": 28,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:24.000000Z"
        },
        {
          "id": 570,
          "name": "Amores Dennis",
          "first_name": "Dennis",
          "last_name": "Amores",
          "email": "dalp22@yahoo.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 6,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:25.000000Z"
        },
        {
          "id": 32,
          "name": "Angel Sandra",
          "first_name": "Sandra",
          "last_name": "Angel",
          "email": "msegu001@hotmail.com",
          "status": "",
          "personal_website": null,
          "account_manager": null,
          "phone_number": null,
          "num_of_locations": 1,
          "num_of_staff": 0,
          "updated_at": "2022-05-19T01:55:18.000000Z"
        }
      ]