export default
    [
        {
          "id": 314,
          "name": "x-Abenaim, Jonathan - Hawthorne",
          "site": [],
          "source": "marchex",
          "account_id": "CtjSZ1MWKuwMGgDQ",
          "hubspot_id": "32098",
          "account_manager": "Nathalie Amar",
          "monthly_fee": null,
          "adwords_budget": "3000",
          "facebook_budget": "2250",
          "facebook_id": null,
          "reporting_mail": "reporting_hawthorne-dental-implants@100marketers.com",
          "website": "hawthorne-dental-implants.com",
          "apexchat_id": "31667",
          "adwords_id": "4100385741",
          "twilio_number": null,
          "address": "1111 Goffle Rd",
          "zipcode": "07506",
          "zip": null,
          "state": "",
          "city": "Hawthorne",
          "phone_numbers": [
            "973-447-4291"
          ],
          "has_ppc": true,
          "has_seo": false,
          "has_apex": true,
          "campaigns": [
            {
              "id": 1044,
              "name": "return#",
              "status": true,
              "description": "return#",
              "phone_number": "973-447-4291",
              "website": "hawthorne-dental-implants.com",
              "f_campaign_id": "fwABAWAF17gISADL",
              "timezone": "US/Eastern",
              "postback_url": "http://marchex.io/euinc/wa/analytics?type=google;gtrackid=UA-187478068-1;gphone=%2Fphonecall%2F973-447-4291;gdomain=hawthorne-dental-implants.com",
              "postback_params": {
                "domain": "hawthorne-dental-implants.com",
                "phone": null,
                "gtrackid": "UA-187478068-1",
                "type": "google"
              }
            }
          ],
          "location_activity_logs": [],
          "client": {
            "id": 41,
            "name": "Abenaim Jonathan",
            "first_name": "Jonathan",
            "last_name": "Abenaim",
            "email": "drabenaim@gmail.com",
            "account_manager_id": 0,
            "phone_number": null,
            "personal_website": null,
            "status": "",
            "deleted_at": null,
            "created_at": "2021-09-06T12:45:33.000000Z",
            "updated_at": "2022-05-19T01:55:18.000000Z"
          },
          "status": null,
          "lh2_api_key": null,
          "created_at": "2021-01-08T19:10:19.000000Z",
          "updated_at": "2022-09-19T00:20:28.000000Z"
        },
        {
          "id": 315,
          "name": "x-Abenaim, Jonathan - SEO",
          "site": [],
          "source": "marchex",
          "account_id": "fwABAV1WtTdN2ADb",
          "hubspot_id": null,
          "account_manager": null,
          "monthly_fee": null,
          "adwords_budget": null,
          "facebook_budget": null,
          "facebook_id": null,
          "reporting_mail": null,
          "website": "jonathandentalspa.com",
          "apexchat_id": null,
          "adwords_id": null,
          "twilio_number": null,
          "address": "1111 Goffle Rd.",
          "zipcode": "07506",
          "zip": null,
          "state": "",
          "city": "Hawthorne",
          "phone_numbers": [],
          "has_ppc": false,
          "has_seo": true,
          "has_apex": false,
          "campaigns": [],
          "location_activity_logs": [],
          "client": {
            "id": 41,
            "name": "Abenaim Jonathan",
            "first_name": "Jonathan",
            "last_name": "Abenaim",
            "email": "drabenaim@gmail.com",
            "account_manager_id": 0,
            "phone_number": null,
            "personal_website": null,
            "status": "",
            "deleted_at": null,
            "created_at": "2021-09-06T12:45:33.000000Z",
            "updated_at": "2022-05-19T01:55:18.000000Z"
          },
          "status": null,
          "lh2_api_key": null,
          "created_at": "2021-01-08T19:10:19.000000Z",
          "updated_at": "2022-09-19T00:20:28.000000Z"
        },
        {
          "id": 1218,
          "name": "x-Abenaim, Jonathan - Geo Fencing",
          "site": [],
          "source": "marchex",
          "account_id": "fwABAWB4YyMhowAq",
          "hubspot_id": null,
          "account_manager": null,
          "monthly_fee": null,
          "adwords_budget": null,
          "facebook_budget": null,
          "facebook_id": null,
          "reporting_mail": "reporting_hawthorne-dental-implants-gf@100marketers.com",
          "website": "hawthorne-dental-implants.com",
          "apexchat_id": null,
          "adwords_id": "4100385741",
          "twilio_number": null,
          "address": "1111 Goffle Road",
          "zipcode": "07506",
          "zip": null,
          "state": "",
          "city": "Hawthorne",
          "phone_numbers": [
            "973-577-7323"
          ],
          "has_ppc": true,
          "has_seo": false,
          "has_apex": false,
          "campaigns": [
            {
              "id": 1117,
              "name": "Default",
              "status": true,
              "description": "Default",
              "phone_number": "973-577-7323",
              "website": "hawthorne-dental-implants.com",
              "f_campaign_id": "fwABAWB4YyQhowAt",
              "timezone": "US/Eastern",
              "postback_url": "http://marchex.io/euinc/wa/analytics?type=google;gtrackid=UA-187478068-1;gphone=%2Fphonecall%2F973-577-7323;gdomain=hawthorne-dental-implants.com",
              "postback_params": {
                "domain": "hawthorne-dental-implants.com",
                "phone": null,
                "gtrackid": "UA-187478068-1",
                "type": "google"
              }
            }
          ],
          "location_activity_logs": [],
          "client": {
            "id": 41,
            "name": "Abenaim Jonathan",
            "first_name": "Jonathan",
            "last_name": "Abenaim",
            "email": "drabenaim@gmail.com",
            "account_manager_id": 0,
            "phone_number": null,
            "personal_website": null,
            "status": "",
            "deleted_at": null,
            "created_at": "2021-09-06T12:45:33.000000Z",
            "updated_at": "2022-05-19T01:55:18.000000Z"
          },
          "status": null,
          "lh2_api_key": null,
          "created_at": "2021-04-15T23:00:03.000000Z",
          "updated_at": "2022-09-19T00:20:28.000000Z"
        },
        {
          "id": 1267,
          "name": "Abenaim",
          "site": [],
          "source": "edge",
          "account_id": "6502919",
          "hubspot_id": null,
          "account_manager": null,
          "monthly_fee": null,
          "adwords_budget": null,
          "facebook_budget": null,
          "facebook_id": null,
          "reporting_mail": null,
          "website": null,
          "apexchat_id": null,
          "adwords_id": null,
          "twilio_number": null,
          "address": null,
          "zipcode": null,
          "zip": null,
          "state": "",
          "city": null,
          "phone_numbers": [
            null
          ],
          "has_ppc": true,
          "has_seo": false,
          "has_apex": false,
          "campaigns": [
            {
              "id": 1268,
              "name": "Abenaim",
              "status": true,
              "description": "Abenaim",
              "phone_number": null,
              "website": null,
              "f_campaign_id": "13301183",
              "timezone": null,
              "postback_url": null,
              "postback_params": {
                "domain": null,
                "phone": null,
                "gtrackid": null,
                "type": null
              }
            }
          ],
          "location_activity_logs": [],
          "client": {
            "id": 41,
            "name": "Abenaim Jonathan",
            "first_name": "Jonathan",
            "last_name": "Abenaim",
            "email": "drabenaim@gmail.com",
            "account_manager_id": 0,
            "phone_number": null,
            "personal_website": null,
            "status": "",
            "deleted_at": null,
            "created_at": "2021-09-06T12:45:33.000000Z",
            "updated_at": "2022-05-19T01:55:18.000000Z"
          },
          "status": null,
          "lh2_api_key": null,
          "created_at": "2021-05-13T23:00:13.000000Z",
          "updated_at": "2022-09-09T20:31:05.000000Z"
        }
      ]